### ISSUE TITLE
Stalling of generateIgram.py on pegasus

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#312] opened 2020-03-12 23:51 UTC
Run the following (or the original script, without 'test'):
```
cd /projects/scratch/insarlab/famelung/KermanshahSenDT79

generateIgram_test.py --master coreg_slaves/20200119 --slave coreg_slaves/20200131 --interferogram testfalk/igram_20200119-20200131
generateIgram.py --master coreg_slaves/20200119 --slave coreg_slaves/20200131 --interferogram testfalk/igram_20200119-20200131
```

The function in the module that gives the problem is  `multiply`. The problem (temporary stalling) occurs after the comment `##### AT THE NEXT LINE`.  It occurs for large (max) lastS values. 

```
def multiply(masname, slvname, outname, rngname1, rngname2, fact, masterFrame,
        flatten=False):

    print('multiply')
    masImg = isceobj.createSlcImage()
    masImg.load( masname + '.xml')

    width = masImg.getWidth()
    length = masImg.getLength()

    ds = gdal.Open(masname + '.vrt', gdal.GA_ReadOnly)
    master = ds.GetRasterBand(1).ReadAsArray()
    ds = None
    ds = gdal.Open(slvname + '.vrt', gdal.GA_ReadOnly)
    slave = ds.GetRasterBand(1).ReadAsArray()
    ds = None
    print('read')
    #master = np.memmap(masname, dtype=np.complex64, mode='r', shape=(length,width))
    #slave = np.memmap(slvname, dtype=np.complex64, mode='r', shape=(length, width))

    if os.path.exists(rngname1):
        rng1 = np.memmap(rngname1, dtype=np.float32, mode='r', shape=(length,width))
    else:
        print('No range offsets provided')
        rng1 = np.zeros((length,width))

    if os.path.exists(rngname2):
        rng2 = np.memmap(rngname2, dtype=np.float32, mode='r', shape=(length,width))
    else:
        print('No range offsets provided')
        rng2 = np.zeros((length,width))

    rng12 = rng2 - rng1

    cJ = np.complex64(-1j)

    #Zero out anytging outside the valid region:
    ifg = np.memmap(outname, dtype=np.complex64, mode='w+', shape=(length,width))
    firstS = masterFrame.firstValidSample
    lastS = masterFrame.firstValidSample + masterFrame.numValidSamples -1
    firstL = masterFrame.firstValidLine
    lastL = masterFrame.firstValidLine + masterFrame.numValidLines - 1
    for kk in range(firstL,lastL + 1):
        ##### AT THE NEXT LINE IT GETS STALLED FOR THE HIGHEST lastL ######
        ifg[kk,firstS:lastS + 1] = master[kk,firstS:lastS + 1] * np.conj(slave[kk,firstS:lastS + 1])
        if flatten:
            phs = np.exp(cJ*fact*rng12[kk,firstS:lastS + 1])
            ifg[kk,firstS:lastS + 1] *= phs


    ####
    master=None
    slave=None
    ifg = None

    objInt = isceobj.createIntImage()
    objInt.setFilename(outname)
    objInt.setWidth(width)
    objInt.setLength(length)
    objInt.setAccessMode('READ')
```

**Comment by mirzaees** [comment] 2020-04-20 16:02
The problem is related to multilooking and since it uses big amount of memory, we need to distribute the jobs. This issue is resolved by separating functions in the run file and assigning less number of jobs to each node.  hopefully it happens less frequently. I am closing this issue for now

**Closed as completed by mirzaees** 2020-04-20 16:02 UTC
